//This file is the parsed network which is created through python.

// The file was generated by RecordedOpModel

#include <limits>
#include <include/mcm/op_model.hpp>
#include "include/mcm/compiler/compilation_unit.hpp"

void build_pySwigCU(mv::OpModel& model)
{
    using namespace mv;

    static const auto inf = std::numeric_limits<double>::infinity();

    const auto Parameter_0 = model.input("Parameter_0", {32, 32, 16, 1}, mv::DType("UInt8"), mv::Order("NHWC"), true);
    const auto Parameter_1 = model.input("Parameter_1", {32, 32, 32, 1}, mv::DType("UInt8"), mv::Order("NHWC"), true);
    auto identity_maxPool_0 = model.maxPool("identity_maxpool_0", Parameter_0, {1,1}, {1,1}, {0,0,0,0}, true);
    auto identity_maxPool_1 = model.maxPool("identity_maxpool_1", Parameter_1, {1,1}, {1,1}, {0,0,0,0}, true);
    const auto Concat_0 = model.concat("Concat_0", {identity_maxPool_0, identity_maxPool_1}, "C");
    const auto output = model.output("", Concat_0);

    Parameter_0->setQuantParams({{0},{1.000000000000000},{-inf},{inf},{0},{1}});
    Parameter_1->setQuantParams({{0},{1.000000000000000},{-inf},{inf},{0},{1}});
    identity_maxPool_0->setQuantParams({{0},{1.000000000000000},{-inf},{inf},{0},{1}});
    identity_maxPool_1->setQuantParams({{0},{1.000000000000000},{-inf},{inf},{0},{1}});
    Concat_0->setQuantParams({{0},{1.000000000000000},{-inf},{inf},{0},{1}});
}

int main()
{
    mv::CompilationUnit unit("parserModel");
    mv::OpModel& om = unit.model();
    build_pySwigCU(om);

    std::string compDescPath = mv::utils::projectRootPath() + "/config/compilation/release_kmb.json";
    unit.loadCompilationDescriptor(compDescPath);
    //Disabling CM Conv for the test
    unit.compilationDescriptor().setPassArg("GlobalConfigParams", "enable_channel_major_conv", mv::Attribute(bool(false)));

    unit.loadTargetDescriptor(mv::Target::ma2490);
    unit.initialize();
    unit.run();

    return 0;
}
