#!/bin/bash

if ! [ -d "build" ] 
then
    mkdir build
fi

# change into build dir and remove any previous build files
cd build
rm -rf *

# build meta files (autogenerated)
cmake ..
make -j8

# generate cross compile build
# rm -rf * //meta folder now in /build
cmake -DCMAKE_TOOLCHAIN_FILE=../cmake-modules/Toolchain.cmake ..
make -j8
