# Importing all previously exported global scons variables
Import('*')

cores_list = []
if 'y' in default_env.subst("$CONFIG_HAS_LRT_SRCS"):
    cores_list.append('lrt')

if 'y' in default_env.subst("$CONFIG_HAS_LNN_SRCS"):
    cores_list.append('lnn')

if cores_list:
    # Compiler includes path
    default_env.addSystemIncludes(default_env.Dir('inc/'), cores_list)
    # Sources
    default_env.addSystemSources(default_env.File(Glob('src/*.c*')), cores_list)
    if 'y' in default_env.subst("$CONFIG_TARGET_SOC_MA2490"):
        default_env.addSystemSources(default_env.File(Glob('src/2490/*.c*')), cores_list)
    if 'y' in default_env.subst("$CONFIG_TARGET_SOC_MA2490_B0"):
        default_env.addSystemSources(default_env.File(Glob('src/2490/*.c*')), cores_list)
    if 'y' in default_env.subst("$CONFIG_TARGET_SOC_3100"):
        default_env.addSystemSources(default_env.File(Glob('src/2490/*.c*')), cores_list)
    if 'y' in default_env.subst("$CONFIG_TARGET_SOC_3600") or 'y' in default_env.subst("$CONFIG_TARGET_SOC_3710") or 'y' in default_env.subst("$CONFIG_TARGET_SOC_3720"):
        default_env.addSystemSources(default_env.File(Glob('src/3600/*.c*')), cores_list)
