
// The file was generated by RecordedOpModel

#include <limits>
#include <include/mcm/op_model.hpp>
#include "include/mcm/compiler/compilation_unit.hpp"

int main()
{
    using namespace mv;

    static const auto inf = std::numeric_limits<double>::infinity();

    mv::CompilationUnit unit("Mixed_mode");
    mv::OpModel& model = unit.model();
    std::string compDescPath = mv::utils::projectRootPath() + "/config/compilation/release_kmb.json";
    unit.loadCompilationDescriptor(compDescPath);
    unit.loadTargetDescriptor(mv::Target::ma2490);

    const auto data_0 = model.input("data", {16, 16, 16, 1}, mv::DType("UInt8"), mv::Order("NHWC"));
    data_0->setQuantParams({{0},{0.00196078431372549},{-inf},{inf},{0},{1}});
    std::vector<int64_t> weightsData0 = {   255,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
                                            255,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
                                            255,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
                                            255,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
                                            255,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
                                            255,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
                                            255,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
                                            255,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
                                            255,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
                                            255,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
                                            255,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
                                            255,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
                                            255,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
                                            255,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
                                            255,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
                                            255,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0};

    auto weights0 = model.constantInt("", weightsData0, {1,1,16,16}, mv::DType("UInt8"), mv::Order("NCHW"));
    auto conv0 = model.conv("conv", data_0, weights0, {1, 1}, {0, 0, 0, 0}, 1, 1);
    weights0->setQuantParams({{0},{0.00392156862745098},{},{}});
    conv0->setQuantParams({{0},{1},{-inf},{inf},{0},{1}});

    model.output("", conv0, mv::DType("Float16"));
    unit.initialize();
    unit.run();
}
