
all: hello vau_exp vau_log vau_sigm vau_tanh

hello:
	bash compile.sh src/hello.c

vau_exp:
	bash compile.sh src/vau_exp.c

vau_log:
	bash compile.sh src/vau_log.c

vau_sigm:
	bash compile.sh src/vau_sigm.c

vau_tanh:
	bash compile.sh src/vau_tanh.c

clean:
	rm -r output


