// RUN: vpux-opt --split-input-file --convert-sw-layers-to-VPUIP %s | FileCheck %s

#NCHW = affine_map<(d0, d1, d2, d3) -> (d0, d1, d2, d3)>

module @Test attributes {VPUIP.arch = "MTL", VPUIP.compilationMode = "ReferenceHW"} {


// CHECK: module @VPU.SW  {
// CHECK:     func private @builtin_Sigmoid(memref<*xf16>, memref<*xf16>) attributes {VPU.kernel_code = "sigmoid_fp16.cpp", VPU.kernel_entry = "sigmoid_fp16"}
// CHECK:     func private @builtin_SoftMax(memref<*xf16>, memref<*xf16>, i64) attributes {VPU.kernel_code = "softmax_fp16.cpp", VPU.kernel_entry = "softmax_fp16"}
// CHECK: func @ThreeSWLayers(%arg0: memref<1x1x1x2000xf16>, %arg1: memref<1x1x1x1000xf16>) -> memref<1x1x1x1000xf16> {

func @ThreeSWLayers(%arg0: memref<1x1x1x2000xf16>, %arg1: memref<1x1x1x1000xf16>) -> memref<1x1x1x1000xf16> {
    %tmp1 = memref.alloc() : memref<1x1x1x2000xf16>
    %tmp2 = memref.alloc() : memref<1x1x1x2000xf16>

    %0 = IERT.SoftMax {axisInd = 3} inputs(%arg0 : memref<1x1x1x2000xf16>) outputs(%tmp1 : memref<1x1x1x2000xf16>) -> memref<1x1x1x2000xf16>
    %1 = IERT.Sigmoid {axisInd = 3} inputs(%0 : memref<1x1x1x2000xf16>) outputs(%tmp2 : memref<1x1x1x2000xf16>) -> memref<1x1x1x2000xf16>

    %2 = IERT.SubView %1[0, 0, 0, 1000] [1, 1, 1, 1000]
        : memref<1x1x1x2000xf16> to memref<1x1x1x1000xf16, {order = #NCHW, strides = [2000, 2000, 2000, 1]}>

    %3 = IERT.SoftMax {axisInd = 3} inputs(%2 : memref<1x1x1x1000xf16, {order = #NCHW, strides = [2000, 2000, 2000, 1]}>) outputs(%arg1 : memref<1x1x1x1000xf16>) -> memref<1x1x1x1000xf16>

    return %3 : memref<1x1x1x1000xf16>

}

}

// CHECK:  %2 = memref.alloc() : memref<1x1x1x2000xf16, "CMX_NN">
// CHECK:  %3 = IERT.Copy inputs(%arg0 : memref<1x1x1x2000xf16>) outputs(%2 : memref<1x1x1x2000xf16, "CMX_NN">) -> memref<1x1x1x2000xf16, "CMX_NN">
// CHECK:  %4 = memref.alloc() : memref<1x1x1x2000xf16, "CMX_NN">
// CHECK:  %5 = VPUIP.SW.Kernel @VPU.SW::@builtin_SoftMax inputs(%3 : memref<1x1x1x2000xf16, "CMX_NN">) outputs(%4 : memref<1x1x1x2000xf16, "CMX_NN">) on tile 0 -> memref<1x1x1x2000xf16, "CMX_NN">  {
// CHECK:       ^bb0(%arg2: memref<1x1x1x2000xf16, "CMX_NN">, %arg3: memref<1x1x1x2000xf16, "CMX_NN">):  // no predecessors
// CHECK:         %c3_i64 = arith.constant 3 : i64
// CHECK:         VPUIP.SW.Kernel.run(%arg2, %arg3, %c3_i64) : memref<1x1x1x2000xf16, "CMX_NN">, memref<1x1x1x2000xf16, "CMX_NN">, i64
// CHECK:       }
// CHECK:  %6 = IERT.Copy inputs(%5 : memref<1x1x1x2000xf16, "CMX_NN">) outputs(%0 : memref<1x1x1x2000xf16>) -> memref<1x1x1x2000xf16>
// CHECK:  %7 = memref.alloc() : memref<1x1x1x2000xf16, "CMX_NN">
// CHECK:  %8 = IERT.Copy inputs(%6 : memref<1x1x1x2000xf16>) outputs(%7 : memref<1x1x1x2000xf16, "CMX_NN">) -> memref<1x1x1x2000xf16, "CMX_NN">
// CHECK:  %9 = memref.alloc() : memref<1x1x1x2000xf16, "CMX_NN">
// CHECK:  %10 = VPUIP.SW.Kernel @VPU.SW::@builtin_Sigmoid inputs(%8 : memref<1x1x1x2000xf16, "CMX_NN">) outputs(%9 : memref<1x1x1x2000xf16, "CMX_NN">) on tile 0 -> memref<1x1x1x2000xf16, "CMX_NN">  {
// CHECK:      ^bb0(%arg2: memref<1x1x1x2000xf16, "CMX_NN">, %arg3: memref<1x1x1x2000xf16, "CMX_NN">):  // no predecessors
// CHECK:       VPUIP.SW.Kernel.run(%arg2, %arg3) : memref<1x1x1x2000xf16, "CMX_NN">, memref<1x1x1x2000xf16, "CMX_NN">
// CHECK:  }
// CHECK:  %11 = IERT.Copy inputs(%10 : memref<1x1x1x2000xf16, "CMX_NN">) outputs(%1 : memref<1x1x1x2000xf16>) -> memref<1x1x1x2000xf16>
// CHECK:  %12 = IERT.SubView %11 [0, 0, 0, 1000] [1, 1, 1, 1000] : memref<1x1x1x2000xf16> to memref<1x1x1x1000xf16, {order = #NCHW, strides = [2000, 2000, 2000, 1]}>
// CHECK:  %13 = memref.alloc() : memref<1x1x1x1000xf16, "CMX_NN">
// CHECK:  %14 = IERT.Copy inputs(%12 : memref<1x1x1x1000xf16, {order = #NCHW, strides = [2000, 2000, 2000, 1]}>) outputs(%13 : memref<1x1x1x1000xf16, "CMX_NN">) -> memref<1x1x1x1000xf16, "CMX_NN">
// CHECK:  %15 = memref.alloc() : memref<1x1x1x1000xf16, "CMX_NN">
// CHECK:  %16 = VPUIP.SW.Kernel @VPU.SW::@builtin_SoftMax inputs(%14 : memref<1x1x1x1000xf16, "CMX_NN">) outputs(%15 : memref<1x1x1x1000xf16, "CMX_NN">) on tile 0 -> memref<1x1x1x1000xf16, "CMX_NN">  {
// CHECK:  ^bb0(%arg2: memref<1x1x1x1000xf16, "CMX_NN">, %arg3: memref<1x1x1x1000xf16, "CMX_NN">):  // no predecessors
// CHECK:  %c3_i64 = arith.constant 3 : i64
// CHECK:  VPUIP.SW.Kernel.run(%arg2, %arg3, %c3_i64) : memref<1x1x1x1000xf16, "CMX_NN">, memref<1x1x1x1000xf16, "CMX_NN">, i64
// CHECK:  }
// CHECK:  %17 = IERT.Copy inputs(%16 : memref<1x1x1x1000xf16, "CMX_NN">) outputs(%arg1 : memref<1x1x1x1000xf16>) -> memref<1x1x1x1000xf16>
// CHECK:  return %17 : memref<1x1x1x1000xf16>
