///
/// INTEL CONFIDENTIAL
/// Copyright 2020. Intel Corporation.
/// This software and the related documents are Intel copyrighted materials, 
/// and your use of them is governed by the express license under which they were provided to you ("License"). 
/// Unless the License provides otherwise, you may not use, modify, copy, publish, distribute, disclose or 
/// transmit this software or the related documents without Intel's prior written permission.
/// This software and the related documents are provided as is, with no express or implied warranties, 
/// other than those that are expressly stated in the License.
///
/// @file      version.h
///
/// @brief     Header for the CMake versioning info. 
///            Contains the functions to access the extern-defined git variables.
///

#ifndef __VERSION_H__
#define __VERSION_H__

#include <string>

// These variables are autogenerated and compiled
// by the Version.cmake script

extern std::string git_commit;
extern std::string git_tag;
extern std::string git_branch;

// This returns the git commit ID as a string
std::string GitCommit()
{
    return git_commit;
}
// This returns the git tag information as a string
std::string GitTag()
{
    return git_tag;
}
// This returns the git branch name as a string
std::string GitBranch()
{
    return git_branch;
}

#endif // __VERSION_H__
