# Importing all previously exported global scons variables
Import('*')

cores_list = ['shave', 'shave_nn']
if 'y' in default_env.subst("$CONFIG_HAS_LRT_SRCS"):
    cores_list.append('lrt')
    # Sources
    default_env.addSystemSources(default_env.File(Glob('src/*.c*')), ['lrt'])

if 'y' in default_env.subst("$CONFIG_HAS_LNN_SRCS"):
    cores_list.append('lnn')
    # Sources
    default_env.addSystemSources(default_env.File(Glob('src/*.c*')), ['lnn'])

# Compiler includes path
default_env.addSystemIncludes(default_env.Dir('inc/'), cores_list)
